### ISSUE TITLE
окак

### ISSUE THREAD

**Issue by Pulij** [fanu-key/discord-lookup#1]
Ку))

**Comment by fanu-key** [comment]
Всё, теперь styles и html шаблон в отдельной папке. Можно компилировать прям так, а после папка не нужна, уже всё в бинарнике.

**Comment by Pulij** [comment]
> Всё, теперь styles и html шаблон в отдельной папке. Можно компилировать прям так, а после папка не нужна, уже всё в бинарнике. 

Понял, понял
